version: '3.4'

services:
  mongodb:
    image: mongo:4.2.12
    container_name: mongodb
    hostname: mongodb
    ports: ["27017:27017"]
  contacts:
    image: yellowdogco/contacts-frontend-assessment:2.0.0
    depends_on:
      - mongodb
    container_name: contacts-frontend-assessment
    hostname: contacts-frontend-assessment
    environment:
      - spring.data.mongodb.host=mongodb
    ports: ["8080:8080"]
